# Generated by Django 5.1 on 2024-08-26 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsapp', '0008_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
    ]
