# Generated by Django 5.1 on 2024-08-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsapp', '0009_remove_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
